[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist/"
  base    = "docs/"

[[redirects]]
  from = "/docs/old.html"
  to = "/docs/test.html"

[[redirects]]
  from = "/old/"
  to = "/test.html"

